name: CI Workflow

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Verificar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Instalar dependencias (si usas Maven o Gradle)
    - name: Install dependencies
      run: mvn install

    # Ejecutar pruebas
    - name: Run tests
      run: mvn test
